version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "8081:3306"  # Exposing MySQL on port 8081
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  spring-petclinic:
    image: nivisha/my-app:latest
    ports:
      - "8082:8080"  # Exposing the Spring app on port 8082
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=petclinic
