version: '3.8'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "8081:3306"  # Change host port to 8081 if 8070 is in use
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  spring-petclinic:
    build:
      context: .
      dockerfile: docker/Dockerfile  # Path to your Dockerfile
    ports:
      - "8082:8080"  # Change host port to 8082 if 8080 is in use
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=petclinic
